import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Sigmar } from 'next/font/google';
import { Roboto } from 'next/font/google';

const sigmar = Sigmar({
   subsets: ['latin'], 
   variable: '--font-sigmar',
   weight: '400',
    display: 'swap' 
  });


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${sigmar.variable}`}>
        {children}
      </body>
    </html>
  );
}
